desc: |
  Captain 自动发布

# 关联IDev
task_idev: &task_idev
  A01:
    name: 点击IDev输入框
    type: CLICK_IMG
    data: idev-input.png
  A02:
    name: 输入IDev
    type: KEYBOARD_INPUT
    data: "3760646"
  A03:
    name: 点击IDev记录
    type: CLICK_IMG
    data: idev-record.png


# 发布UAT
task_publish_uat:
  C01:
    name: 关联IDev
    type: SUB_MISSIONS
    data: *task_idev
  C02:
    name: 点击UAT开关
    type: CLICK_IMG
    data: uat-switch.png
  C02_1:
    name: 审批通过
    type: CLICK_IMG
    data: check_pass.png
  C03:
    name: 点击UAT发布
    type: CLICK_IMG
    data: uat-publish.png
  C07:
    name: 点击选择Group
    type: CLICK_IMG
    data: group-select.png
  D03:
    name: 点击Uat
    type: CLICK_IMG
    data: uat-group.png
  D04:
    name: 点击下一步
    type: CLICK_IMG
    data: next.png
  D05:
    name: 点击新建
    type: CLICK_IMG
    data: new.png


# 发布DEVB
task_publish_devb:
  C04:
    name: 点击PRO开关
    type: CLICK_IMG
    data: pro-switch.png
  C02_1:
    name: 审批通过
    type: CLICK_IMG
    data: check_pass.png
  C06:
    name: 点击PRO发布
    type: CLICK_IMG
    data: pro-release.png
  C07:
    name: 点击选择Group
    type: CLICK_IMG
    data: group-select.png
  D02:
    name: 输入DevB
    type: KEYBOARD_INPUT
    data: dev_b
    config:
      sleep: 1.5
  D03:
    name: 点击DevB
    type: CLICK_IMG
    data: dev_b.png
  D04:
    name: 点击下一步
    type: CLICK_IMG
    data: next.png
  D05:
    name: 点击新建
    type: CLICK_IMG
    data: new.png
  D06:
    name: 点击跳转B
    type: CLICK_IMG
    data: jump-b.png


## old blow

# 前置检查
task_check: &task_check
  B01:
    name: 点击原因输入框
    type: CLICK_IMG
    data: pre-check.png
  B02:
    name: 点击其他选项
    type: CLICK_IMG
    data: pre-check-other.png
  B03:
    name: 点击理由输入框
    type: CLICK_IMG
    data: pre-check-reason.png
  B04:
    name: 输入理由
    type: KEYBOARD_INPUT
    data: "Temporary  release  Temporary  release "
  B05:
    name: 点击审批通过
    type: CLICK_IMG
    data: pre-check-approve.png

# 发布DevB
task_publish_b_with_check:
  C01:
    name: 关联IDev
    type: SUB_MISSIONS
    data: *task_idev
  C02:
    name: 点击UAT开关
    type: CLICK_IMG
    data: uat-switch.png
  C03:
    name: 前置检查
    type: SUB_MISSIONS
    data: *task_check
  C04:
    name: 点击PRO开关
    type: CLICK_IMG
    data: pro-switch.png
  C05:
    name: 前置检查
    type: SUB_MISSIONS
    data: *task_check
  C06:
    name: 点击PRO发布
    type: CLICK_IMG
    data: pro-release.png
  C07:
    name: 点击选择Group
    type: CLICK_IMG
    data: group-select.png
  D02:
    name: 输入DevB
    type: KEYBOARD_INPUT
    data: dev_b
    config:
      sleep: 1.5
  D03:
    name: 点击DevB
    type: CLICK_IMG
    data: dev_b.png
  D04:
    name: 点击下一步
    type: CLICK_IMG
    data: next.png
  D05:
    name: 点击新建
    type: CLICK_IMG
    data: new.png
  D06:
    name: 点击跳转B
    type: CLICK_IMG
    data: jump-b.png