desc: |
  自动信安会话审批

pre_process: &pre_process
  A01:
    name: 打开网址
    type: OPEN_URL
    data: http://jumpserver.audit.infosec.ctripcorp.com/#/mysession
  A02:
    name: 点击处理
    type: CLICK_IMG
    data: handle.png

handle_process: &handle_process
  B01:
    name: 点击请选择
    type: CLICK_IMG
    data: select.png
  B02:
    name: 点击查看/检查
    type: CLICK_IMG
    data: check.png
  B03:
    name: 点击请输入
    type: CLICK_IMG
    data: input.png
  B04:
    name: 输入内容
    type: KEYBOARD_INPUT
    data: OPS
  B05:
    name: 点击提交
    type: CLICK_IMG
    data: submit.png
    config:
      condition: 0.9

handles:
  <<: *pre_process
  <<: *handle_process
  C01:
    name: 子任务集合
    type: SUB_MISSIONS
    data: *handle_process
    config:
      times: 20

