desc: |
  自动信安会话审批

pre_process: &pre_process
  A01:
    name: 打开网址
    type: OPEN_URL
    data: http://jumpserver.audit.infosec.ctripcorp.com/#/mysession
    config:
      sleep: 5
  A02:
    name: 点击处理
    type: CLICK_TEXT
    data: 处理

handle_process: &handle_process
  B01:
    name: 点击请选择
    type: CLICK_TEXT
    data: 请选择
  B02:
    name: 点击查看/检查
    type: CLICK_TEXT
    data: 查看/检查
  B03:
    name: 点击请输入
    type: CLICK_TEXT
    data: 请输入
  B04:
    name: 输入内容
    type: KEYBOARD_INPUT
    data: OPS
  B05:
    name: 点击提交
    type: CLICK_TEXT
    data: 提交

handle_20:
  <<: *pre_process
  <<: *handle_process
