desc: |
  Qconfig 自动发布

task_idev: &task_idev
  - op_name: 点击IDev输入框
    op_type: click
    data:
      path: idev-input.png
      confidence: 0.8
    interval: 1
  - op_name: 输入IDev
    op_type: input
    data: "3760646"
  - op_name: 点击IDev记录
    op_type: click
    data: idev-record.png